networks:
  quote-api:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: brand_scout_test_db
    networks:
      - quote-api
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quote-api
    ports:
      - "8888:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  quote-api:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - quote-api
    hostname: quote-api
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DSN: "host=postgres user=postgres password=postgres dbname=quote-api port=5432 sslmode=disable"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
